### ISSUE TITLE
前端构建缺少配置文件

### ISSUE THREAD

**Issue by flashjay** [aimerforreimu/auxpi#72]
## Bug report（问题描述）
前端构建缺少配置文件
#### Steps to reproduce（问题复现步骤）

1. yarn build

yarn run v1.17.0
warning package.json: License should be a valid SPDX license expression
$ node build/build.js
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module '/Users/xxx/work/github/beego/auxpi/resource/build/build.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',

2. yarn start

yarn run v1.17.0
warning package.json: License should be a valid SPDX license expression
$ npm run dev
npm WARN lifecycle The node binary used for scripts is /var/folders/nr/b6knyz691y7b739097d3139w0000gn/T/yarn--1563272182442-0.5503449220725973/node but npm is using /usr/local/Cellar/node/12.6.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

 Auxpi-Admin@2.0.1 dev /Users/xxx/work/github/beego/auxpi/resource
 webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

internal/modules/cjs/loader.js:628
    throw err;

#### Server environment（服务器环境）
- Your OS & version (服务器系统&版本):
- DataBase & version (数据库&版本):

#### Other relevant information（格外信息）
- auxpi version:dev

**Comment by flashjay** [comment]
解决方法参考 #73
