### ISSUE TITLE
脚本update后，无法运行，错误日志如下

### ISSUE THREAD

**Issue by bterys** [aimerforreimu/auxpi#82]
`` is not officially supported, running under compatibility mode.
2019/09/09 18:31:43 &{<nil> <nil> 0 <nil> false 0 {0xc0001b0410} <nil> {{0 0} {<nil>} map[] 0} 0xc0000b8dc0 0x10977e0 0xc0001c3d40 false}
2019/09/09 18:31:43 sql: unknown driver "" (forgotten import?)
2019/09/09 18:31:43 [info] replacing callback `gorm:update_time_stamp` from /Users/aimer/go/src/github.com/auxpi/models/models.go:80
2019/09/09 18:31:43 [info] replacing callback `gorm:update_time_stamp` from /Users/aimer/go/src/github.com/auxpi/models/models.go:81
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8cb996]

goroutine 1 [running]:
database/sql.(*DB).SetMaxIdleConns(0x0, 0xa)
	/usr/local/Cellar/go/1.11/libexec/src/database/sql/sql.go:814 +0x26
github.com/auxpi/models.init.0()
	/Users/aimer/go/src/github.com/auxpi/models/models.go:84 +0x85a

**Comment by wq163** [comment]
我也是
